#!/bin/bash

COMMIT_MSG_FILE="$1"
COMMIT_SOURCE="$2"
SHA1="$3"

BRANCH_NAME=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD)

case "$COMMIT_SOURCE" in
  message)
    echo "$COMMIT_MSG_FILE"
    ;;
  *)
    if [ -n "$BRANCH_NAME" ]; then
      echo "[$BRANCH_NAME] $(cat "$COMMIT_MSG_FILE")" > "$COMMIT_MSG_FILE"
    fi
    ;;
esac
