---

name: CLA

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cla:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bniladridas/cla-bot@v1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
