---
name: Databricks Dockerize

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: "dev"
        type: "string"

jobs:
  dockerize:
    name: Dockerize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: "."
          file: "Dockerfile"
          push: false
          tags: "lifeboat:${{ github.sha }}"
